config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :menus
  resources :orders
  resources :invoices
  resources :users
  root "welcomes#index"
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	belongs_to :order
	validates :code, presence: true, length: { is: 6 }
	validates :amount, presence: true, numericality: true 
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
	protect_from_forgery
  def index
    @invoices = Invoice.all
    respond_to do |format|
      format.json { render json: { invoices: @invoices }, status: :ok }
      format.html
    end
  end

  def new
    @invoice = Invoice.new
  end 
  
  def show
    begin
      @invoice = Invoice.find(params[:id])
      respond_to do |format|
        format.json { render json: { invoice: @invoice }, status: :ok }
        format.html
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :unprocessable_entity
    end
  end
  
  def edit
    begin
      @invoice = Invoice.find(params[:id])
      respond_to do |format|
        format.json { render json: { invoice: @invoice }, status: :ok }
        format.html
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
    end
  end
 
  def create
  	@invoice = Invoice.new(invoice_params)
    if @invoice.save
      respond_to do |format|
        format.json { render json: { invoice: @invoice }, status: :ok }
        format.html { redirect_to invoices_path }
      end
    else
      respond_to do |format|
        format.json { render json: { invoice: @invoice.errors }, status: :unprocessable_entity }
        format.html { redirect_to new_invoice_path }
      end
    end
  end

  def update
    begin
      @invoice = Invoice.find(params[:id])
      if @invoice.update(invoice_params)
        redirect_to @invoice
      else
        respond_to do |format|
          format.json { render json: { invoice: @invoice.errors }, status: :unprocessable_entity }
          format.html { redirect_to edit_invoice_path }
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
    end
  end
  
  def destroy
    begin
      @invoice = Invoice.find(params[:id])
      if @invoice.destroy
        respond_to do |format|
          format.json { render json: { message: 'Invoice was deleted successfully' }, status: :ok }
          format.html { redirect_to invoices_path }
        end
      else
        respond_to do |format|
          format.json { render json: { invoice: @invoice.errors }, status: :unprocessable_entity }
          format.html
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
    end
  end

  private
  def invoice_params
    params.require(:invoice).permit(:code, :amount, :order_id)
  end
end

app/views/invoices/_form.html.erb
<%= form_for [@invoice], local: true do |form| %>
  <p>
    <%= form.label :Code %><br>
    <%= form.text_field :code %>
  </p>
  <p>
    <%= form.label :Amount %><br>
    <%= form.text_field :amount %>
  </p>
  <%= hidden_field_tag(:order_id, params[:order_id]) %> 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/invoices/edit.html.erb
<center>
	<h1>Edit Invoice</h1>
	<%= render 'form' %>
	<%= link_to 'Back', invoices_path %>
</center>

app/views/invoices/index.html.erb
<center>
  <h1>Listing Invoices</h1>
  <br><br>
  <table cellpadding="10">
    <tr>
      <th>Code</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.code %></td>
        <td><%= invoice.amount %></td>
        <td><%= link_to 'Show', invoice_path(invoice) %></td>
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Delete', invoice_path(invoice), :method => :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
  <%= link_to 'Back To Restaurants', restaurants_path %>
</center>

app/views/invoices/new.html.erb
<center>
	<h1>New Invoice</h1>
	<%= render 'form' %>
	<%= link_to 'Back', invoices_path %>
</center>

app/views/invoices/show.html.erb
<center>
	<h3>Invoices</h3>
	<p>
	  <strong>Code:</strong>
	  <%= @invoice.code %>
	</p>
	<p>
	  <strong>Amount:</strong>
	  <%= @invoice.amount %>
	</p>
	<%= link_to 'Back', invoices_path %>
</center>