config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :menus
  resources :orders
  resources :invoices
  resources :users
  root "welcomes#index"
end

app/models/user.rb
class User < ActiveRecord::Base
	belongs_to :restaurant
	has_many :orders, dependent: :destroy
	validates :name, presence: true
	validates :address, presence: true
	validates :phone_no, presence: true, length: { maximum: 17, minimum: 5 }, numericality: { only_integer: true }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	protect_from_forgery
  def index
    @users = User.all
    respond_to do |format|
      format.json { render json: { users: @users }, status: :ok }
      format.html
    end
  end
  
  def new
    @user = User.new
  end 

  def show
    begin
      @user = User.find(params[:id])
      respond_to do |format|
        format.json { render json: { user: @user }, status: :ok }
        format.html
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :unprocessable_entity
    end
  end

  def edit
    begin
      @user = User.find(params[:id])
      respond_to do |format|
        format.json { render json: { user: @user }, status: :ok }
        format.html
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
    end
  end
 
  def create
  	@user = User.new(user_params)
    if @user.save
      respond_to do |format|
        format.json { render json: { user: @user }, status: :ok }
        format.html { redirect_to users_path }
      end
    else
      respond_to do |format|
        format.json { render json: { user: @user.errors }, status: :unprocessable_entity }
        format.html { redirect_to new_user_path }
      end
    end
  end

  def update
    begin
      @user = User.find(params[:id])
      if @user.update(user_params)
        redirect_to @user
      else
        respond_to do |format|
          format.json { render json: { user: @user.errors }, status: :unprocessable_entity }
          format.html { redirect_to edit_user_path }
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
    end
  end
  
  def destroy
    begin
      @user = User.find(params[:id])
      if @user.destroy
        respond_to do |format|
          format.json { render json: { message: 'User was deleted successfully' }, status: :ok }
          format.html { redirect_to users_path }
        end
      else
        respond_to do |format|
          format.json { render json: { user: @user.errors }, status: :unprocessable_entity }
          format.html
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :address, :phone_no, :restaurant_id)
  end
end

app/views/users/_form.html.erb
<%= form_for [@restaurant, @user], local: true do |form| %>
  <p>
    <%= form.label :Name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :Address %><br>
    <%= form.text_field :address %>
  </p>
  <p>
    <%= form.label :Phone_No %><br>
    <%= form.text_field :phone_no %>
  </p>
  <%= hidden_field_tag(:restaurant_id, params[:restaurant_id]) %> 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<center>
  <h1>Edit User</h1>
  <%= render 'form' %>
  <%= link_to 'Back', users_path %>
</center>

app/views/users/index.html.erb
<center>
  <h1>Listing Users</h1>
  <table cellpadding="10">
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone No</th>
      <th colspan="4"></th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.address %></td>
        <td><%= user.phone_no %></td>
        <td><%= link_to 'Show', user_path(user) %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Delete', user_path(user), :method => :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
  <%= link_to 'Back To Restaurants', restaurants_path %>
</center>

app/views/users/new.html.erb
<center>
  <h1>New User</h1>
  <%= render 'form' %>
  <%= link_to 'Back', users_path %>
</center>

app/views/users/show.html.erb
<center>
  <h3>User</h3>
  <p>
    <strong>Name:</strong>
    <%= @user.name %>
  </p>
  <p>
    <strong>Address:</strong>
    <%= @user.address %>
  </p>
  <p>
    <strong>Phone No:</strong>
    <%= @user.phone_no %>
  </p>
  <%= link_to 'Back', users_path %>
</center>