config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :menus
  resources :orders
  resources :invoices
  resources :users
  root "welcomes#index"
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :menu
	belongs_to :user
	has_one :invoice, dependent: :destroy
	validates :code, presence: true, length: { is: 6 }
	validates :food_details_with_quantity, presence: true
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	protect_from_forgery
  def index
    @orders = Order.all
    respond_to do |format|
      format.json { render json: { orders: @orders }, status: :ok }
      format.html
    end
  end
  
  def new
    @order = Order.new
  end 

  def show
    begin
      @order = Order.find(params[:id])
      respond_to do |format|
        format.json { render json: { order: @order }, status: :ok }
        format.html
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :unprocessable_entity
    end
  end
 
  def edit
    begin
      @order = Order.find(params[:id])
      respond_to do |format|
        format.json { render json: { order: @order }, status: :ok }
        format.html
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
    end
  end
 
  def create
  	@order = Order.new(order_params)
    if @order.save
      respond_to do |format|
        format.json { render json: { order: @order }, status: :ok }
        format.html { redirect_to orders_path }
      end
    else
      respond_to do |format|
        format.json { render json: { order: @order.errors }, status: :unprocessable_entity }
        format.html { redirect_to new_order_path }
      end
    end
  end

  def update
    begin
      @order = Order.find(params[:id])
      if @order.update(order_params)
        redirect_to @order
      else
        respond_to do |format|
          format.json { render json: { order: @order.errors }, status: :unprocessable_entity }
          format.html { redirect_to edit_order_path }
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
    end
  end
  
  def destroy
    begin
      @order = Order.find(params[:id])
      if @order.destroy
        respond_to do |format|
          format.json { render json: { message: 'Order was deleted successfully' }, status: :ok }
          format.html { redirect_to orders_path }
        end
      else
        respond_to do |format|
          format.json { render json: { order: @order.errors }, status: :unprocessable_entity }
          format.html
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
    end
  end

  private
  def order_params
    params.require(:order).permit(:code, :food_details_with_quantity, :menu_id, :user_id)
  end
end

app/views/orders/_form.html.erb
<%= form_for [@order], local: true do |form| %>
  <p>
    <%= form.label :Code %><br>
    <%= form.text_field :code %>
  </p>
  <p>
    <%= form.label :Food_Details_With_Quantity %><br>
    <%= form.text_field :food_details_with_quantity %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/orders/edit.html.erb
<center>
  <h1>Edit Order</h1>
  <%= render 'form' %>
  <%= link_to 'Back', orders_path %>
</center>

app/views/orders/index.html.erb
<center>
  <h1>Listing Orders</h1><br>
  Click to <td><%= link_to 'Add Orders', new_order_path%></td><br>
  <table cellpadding="10">
    <tr>
      <th>Code</th>
      <th>Food_Details_With_Quantity</th>
      <th colspan="3"></th>
    </tr>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.code %></td>
        <td><%= order.food_details_with_quantity %></td>
        <td><%= link_to 'Show', order_path(order) %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Delete', order_path(order), :method => :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Add Invoice', new_invoice_path(:order_id => order.id)%></td>
      </tr>
    <% end %>
  </table>
  <%= link_to 'Back To Restaurants', restaurants_path %>
</center>

app/views/orders/new.html.erb
<center>
  <h1>New Order</h1>
  <%= render 'form' %>
  <%= link_to 'Back', orders_path %>
</center>

app/views/orders/show.html.erb
<center>
  <h3>Orders</h3>
  <p>
    <strong>Code:</strong>
    <%= @order.code %>
  </p>
  <p>
    <strong>Food_Details_With_Quantity:</strong>
    <%= @order.food_details_with_quantity %>
  </p>
  <%= link_to 'Back', orders_path %>
</center>