config/routes.rb
Rails.application.routes.draw do
  resources :restaurants
  resources :menus
  resources :orders
  resources :invoices
  resources :users
  root "welcomes#index"
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :users, dependent: :destroy
	has_many :menus, dependent: :destroy
	validates :name, presence: true
	validates :address, presence: true
	validates :city, presence: true
	validates :phone_no, presence: true, length: { maximum: 17, minimum: 5 }, numericality: { only_integer: true }
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	protect_from_forgery
  def index
    @restaurants = Restaurant.all
    respond_to do |format|
      format.json { render json: { restaurants: @restaurants }, status: :ok }
      format.html
    end
  end
  
  def new
    @restaurant = Restaurant.new
  end 

  def show
    begin
      @restaurant = Restaurant.find(params[:id])
      respond_to do |format|
        format.json { render json: { restaurant: @restaurant }, status: :ok } 
        format.html
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :unprocessable_entity
    end
  end

  def edit
    begin
      @restaurant = Restaurant.find(params[:id])
      respond_to do |format|
        format.json { render json: { restaurant: @restaurant }, status: :ok }
        format.html
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
    end
  end
 
  def create
  	@restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      respond_to do |format|
        format.json { render json: { restaurant: @restaurant }, status: :ok }
        format.html { redirect_to restaurants_path }
      end
    else
      respond_to do |format|
        format.json { render json: { restaurant: @restaurant.errors }, status: :unprocessable_entity }
        format.html { redirect_to new_restaurant_path }
      end
    end
  end

  def update
    begin
      @restaurant = Restaurant.find(params[:id])
      if @restaurant.update(restaurant_params)
        redirect_to @restaurant
      else
        respond_to do |format|
          format.json { render json: { restaurant: @restaurant.errors }, status: :unprocessable_entity }
          format.html { redirect_to edit_restaurant_path }
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
    end
  end
  
  def destroy
    begin
      @restaurant = Restaurant.find(params[:id])
      if @restaurant.destroy
        respond_to do |format|
          format.json { render json: { message: 'Restaurant was deleted successfully' }, status: :ok }
          format.html { redirect_to restaurants_path }
        end
      else
        respond_to do |format|
          format.json { render json: { restaurant: @restaurant.errors }, status: :unprocessable_entity }
          format.html
        end
      end
    rescue ActiveRecord::RecordNotFound => e
      render json: { error: e.message }, status: :not_found
    end
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :city, :phone_no, :rating, :is_veg, :has_bar)
  end
end

app/views/restaurants/_form.html.erb
<%= form_for @restaurant, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :address %><br>
    <%= form.text_field :address %>
  </p>
   <p>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  </p>
   <p>
    <%= form.label :phone_no %><br>
    <%= form.text_field :phone_no %>
  </p>
   <p>
    <%= form.label :rating %><br>
    <%= form.text_field :rating %>
  </p>
   <p>
    <%= form.label :is_veg %><br>
    <%= form.text_field :is_veg %>
  </p>
   <p>
    <%= form.label :has_bar %><br>
    <%= form.text_field :has_bar %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/restaurants/edit.html.erb
<center>
  <h1>Edit Restaurant</h1>
  <%= render 'form' %>
  <%= link_to 'Back', restaurants_path %>
</center>

app/views/restaurants/index.html.erb
<center>
  <h1>Listing Restaurants</h1>
   Click to create <%= link_to 'New Restaurant', new_restaurant_path %><br><br>
   Click to <%= link_to 'Display Orders', orders_path %>
  <br><br>
  <table cellpadding="10">
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>Phone No</th>
      <th>Rating</th>
      <th>Is Vegan?</th>
      <th>Has Bar?</th>
      <th colspan="8"></th>
    </tr>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.city %></td>
        <td><%= restaurant.phone_no %></td>
        <td><%= restaurant.rating %></td>
        <td><%= restaurant.is_veg %></td>
        <td><%= restaurant.has_bar %></td>
        <td><%= link_to 'Show', restaurant_path(restaurant) %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Delete', restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' } %> </td>
        <td><%= link_to 'Add Menu', new_menu_path(:restaurant_id => restaurant.id)%></td>
        <td><%= link_to 'Add User', new_user_path(:restaurant_id => restaurant.id)%></td>
      </tr>
    <% end %>
  </table>
</center>

app/views/restaurants/new.html.erb
<center>
  <h1>New Restaurant</h1>
  <%= render 'form' %>
  <%= link_to 'Back', restaurants_path %>
</center>

app/views/restaurants/show.html.erb
<center>
  <h3>Restaurant Details</h3>
  <p>
    <strong>Name:</strong>
    <%= @restaurant.name %>
  </p>
  <p>
    <strong>Address:</strong>
    <%= @restaurant.address %>
  </p>
  <p>
    <strong>City:</strong>
    <%= @restaurant.city %>
  </p>
  <p>
    <strong>Phone Number:</strong>
    <%= @restaurant.phone_no %>
  </p>
  <p>
    <strong>Rating:</strong>
    <%= @restaurant.rating %>
  </p>
  <p>
    <strong>Is Vegan?:</strong>
    <%= @restaurant.is_veg %>
  </p>
  <p>
    <strong>Has Bar?:</strong>
    <%= @restaurant.has_bar %>
   </p>
  <%= link_to 'Back', restaurants_path %>
</center>